# Generated by Django 6.0 on 2025-12-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Manual size input (e.g. M, 42, 10-12)', max_length=100, verbose_name='Size'),
        ),
    ]
