# Generated by Django 6.0 on 2025-12-08 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='difference',
            field=models.CharField(blank=True, help_text='One word describing the difference (e.g., Color, Style, Pattern)', max_length=50),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which variants appear'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_product',
            field=models.ForeignKey(blank=True, null=True, help_text='The actual product variant (full product instance)', on_delete=django.db.models.deletion.CASCADE, related_name='parent_variants', to='store.product'),
        ),
        # Note: unique_together with nullable field - Django allows multiple NULLs
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'variant_product')},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_product',
            field=models.ForeignKey(blank=True, help_text='Variant product (full product instance)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items_as_variant', to='store.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_size',
            field=models.CharField(blank=True, help_text='Size selected at purchase', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_product',
            field=models.ForeignKey(blank=True, help_text='Variant product used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_as_variant', to='store.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(help_text='Main product this variant belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product'),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Size')),
                ('stock_count', models.PositiveIntegerField(default=0, help_text='Stock available for this size')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which sizes appear')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.product')),
            ],
            options={
                'ordering': ['sort_order', 'size'],
                'unique_together': {('product', 'size')},
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_size',
            field=models.ForeignKey(blank=True, help_text='Selected size (independent from variant)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productsize'),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price_adjustment',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_count',
        ),
    ]
