# Generated by Django 6.0 on 2025-12-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='related_variants',
            field=models.ManyToManyField(blank=True, help_text='All variants related to this one (no parent-child hierarchy)', related_name='related_to_variants', to='store.productvariant'),
        ),
    ]
