# Generated by Django 6.0 on 2025-12-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_returnrequest_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when order was marked as delivered', null=True),
        ),
    ]
