# Generated by Django 6.0 on 2025-12-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Display this category on home page'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Display this product on home page (new arrivals)'),
        ),
    ]
